# -*- coding: utf-8 -*-
"""Face detection FHF

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oc7bNZZh-5b4m_btJ5H_N_FzMJTD6YwQ
"""

!pip install opencv-python

!pip install deepface

!pip install matplotlib

import cv2
from deepface import DeepFace

import matplotlib.pyplot as plt

img = cv2.imread('IMG_20231018_233252.jpg')         #here we have to copy the img file path
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('happy1.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('happy2.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('happy4.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('happy5.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('sad5.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('sadd.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('angry1.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('angry2.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('angry3.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('angry4.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('angry6.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('suprise.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('disgust2.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('disgust5.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('1.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('2.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('3.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('4.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('5.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('6.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('7.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('8.jpg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('10.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('11.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('12.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('13.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('14.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('15.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions

img = cv2.imread('16.jpeg')
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
predictions=DeepFace.analyze(img,enforce_detection= False)
predictions